services:
  db_test:
    image: postgres:alpine
    user: postgres
    container_name: db_test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      PGPORT: ${DB_PORT}
    expose:
      - "5433"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test && psql -U test" ]
      interval: 5s
      timeout: 3s
      retries: 10

  api_test:
    container_name: api_test
    build:
      context: .
      dockerfile: Dockertest
    depends_on:
      db_test:
        condition: service_healthy
    ports:
     - ${PORT}:${PORT}
    environment:
      DATABASE_URL: "postgres://cosyl:cosyl@db_test:5433/cosyl"
      DATABASE_TEST_URL: "postgres://test:test@db_test:5433/test"
      PORT: "3046"
      DB_PORT: "5433"
      DEBUG: "false"
    tmpfs:
      - /tmp

volumes:
  pgdata_test: