services:
  db:
    image: postgres:alpine
    user: postgres
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} && psql -U ${DB_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - internal

  api:
    container_name: api
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
     - $PORT:$PORT
    restart: always
    tmpfs:
      - /tmp
    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
    driver: bridge