services:
  db:
    image: postgres:alpine
    user: postgres
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres && psql -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - internal

  web:
    container_name: web
    image: caddy:2.4.6-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/internal/web/www:/var/www
      - $PWD/internal/web/Caddyfile:/etc/caddy/Caddyfile
      - tmp:/var/www/tmp
    networks:
      - internal

  api:
    container_name: api
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
     - 2046:2046
    restart: always
    volumes:
      - tmp:/app/tmp
    networks:
      - internal


volumes:
  pgdata:
  tmp:

networks:
  internal:
    driver: bridge