services:
  db_test_viewer:
    image: postgres:alpine
    user: postgres
    container_name: db_test_viewer
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: viewer-test
      PGPORT: "5433"
    expose:
      - "5433"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d viewer-test && psql -U test -d viewer-test" ]
      interval: 5s
      timeout: 3s
      retries: 10

  backend_test_viewer:
    container_name: backend_test_viewer
    build:
      context: .
      dockerfile: tests/Dockertest.back
    depends_on:
      db_test_viewer:
        condition: service_healthy
    ports:
     - ${PORT}:${PORT}
    environment:
      DATABASE_URL: "postgres://cosyl:cosyl@db_test_viewer:5433/cosyl"
      DATABASE_TEST_URL: "postgres://test:test@db_test_viewer:5433/viewer-test"
      PORT: "3046"
      DB_PORT: "5433"
      DEBUG: "false"
      TEST: "true"
    tmpfs:
      - /tmp

  backend_viewer:
    container_name: backend_viewer
    build: .
    depends_on:
      db_test_viewer:
        condition: service_healthy
    ports:
     - ${PORT}:${PORT}
    environment:
      DATABASE_URL: "postgres://test:test@db_test_viewer:5433/viewer-test"
      DATABASE_TEST_URL: "postgres://test:test@db_test_viewer:5433/viewer-test"
      PORT: "3046"
      DB_PORT: "5433"
      DEBUG: "false"
      TEST: "true"
    tmpfs:
      - /tmp

  frontend_test_viewer:
    image: cypress
    build:
      context: .
      dockerfile: tests/Dockertest.front
    depends_on:
      - backend_viewer
    environment:
      - CYPRESS_baseUrl=http://backend_viewer:3046
    volumes:
      - ./www/cypress:/app/cypress

volumes:
  pgdata_test: