// Code generated by zek; DO NOT EDIT.

package specs

import "encoding/xml"

// Manifest was generated 2022-03-29 17:02:15 by pierre on archpierre.
type Manifest struct {
	XMLName        xml.Name `xml:"manifest"`
	Text           string   `xml:",chardata"`
	Identifier     string   `xml:"identifier,attr"`
	Xmlns          string   `xml:"xmlns,attr"`
	Lom            string   `xml:"lom,attr"`
	Lomimscc       string   `xml:"lomimscc,attr"`
	Xsi            string   `xml:"xsi,attr"`
	SchemaLocation string   `xml:"schemaLocation,attr"`
	Metadata       struct {
		Text          string `xml:",chardata"`
		Schema        string `xml:"schema"`
		Schemaversion string `xml:"schemaversion"`
		Lom           struct {
			Text    string `xml:",chardata"`
			General struct {
				Text  string `xml:",chardata"`
				Title struct {
					Text   string `xml:",chardata"`
					String struct {
						Text     string `xml:",chardata"`
						Language string `xml:"language,attr"`
					} `xml:"string"`
				} `xml:"title"`
				Description struct {
					Text   string `xml:",chardata"`
					String struct {
						Text     string `xml:",chardata"`
						Language string `xml:"language,attr"`
					} `xml:"string"`
				} `xml:"description"`
				Keyword struct {
					Text   string `xml:",chardata"`
					String struct {
						Text     string `xml:",chardata"`
						Language string `xml:"language,attr"`
					} `xml:"string"`
				} `xml:"keyword"`
			} `xml:"general"`
		} `xml:"lom"`
	} `xml:"metadata"`
	Organizations struct {
		Text         string `xml:",chardata"`
		Organization struct {
			Text       string `xml:",chardata"`
			Identifier string `xml:"identifier,attr"`
			Structure  string `xml:"structure,attr"`
			Item       Item `xml:"item"`
		} `xml:"organization"`
	} `xml:"organizations"`
	Resources struct {
		Text     string `xml:",chardata"`
		Resource []Resource `xml:"resource"`
	} `xml:"resources"`
}
