// Code generated by zek; DO NOT EDIT.

package specs

import "encoding/xml"

// Item was generated 2022-03-29 17:02:15 by pierre on archpierre.
type Item struct {
	XMLName    xml.Name `xml:"item"`
	Text       string   `xml:",chardata"`
	Identifier string   `xml:"identifier,attr"`
	Identifierref string `xml:"identifierref,attr"`
	Item       []Item `xml:"item"`
}
