// Code generated by zek; DO NOT EDIT.

package specs

import "encoding/xml"

// Resource was generated 2022-03-29 17:02:15 by pierre on archpierre.
type Resource struct {
	XMLName    xml.Name `xml:"resource"`
	Text       string   `xml:",chardata"`
	Href       string   `xml:"href,attr"`
	Identifier string   `xml:"identifier,attr"`
	Type       string   `xml:"type,attr"`
	File       struct {
		Text string `xml:",chardata"`
		Href string `xml:"href,attr"`
	} `xml:"file"`
	Metadata struct {
		Text string `xml:",chardata"`
		Lom  struct {
			Text        string `xml:",chardata"`
			Educational struct {
				Text                string `xml:",chardata"`
				IntendedEndUserRole struct {
					Text   string `xml:",chardata"`
					Source string `xml:"source"`
					Value  string `xml:"value"`
				} `xml:"intendedEndUserRole"`
			} `xml:"educational"`
		} `xml:"lom"`
	} `xml:"metadata"`
	Dependency []struct {
		Text          string `xml:",chardata"`
		Identifierref string `xml:"identifierref,attr"`
	} `xml:"dependency"`
}
