// Code generated by zek; DO NOT EDIT.

package commoncartridge

import "encoding/xml"

// Assignment was generated 2022-04-06 17:47:57 by pierre on archpierre.
type Assignment struct {
	XMLName        xml.Name `xml:"assignment"`
	Chardata       string   `xml:",chardata"`
	Identifier     string   `xml:"identifier,attr"`
	Xmlns          string   `xml:"xmlns,attr"`
	Xsi            string   `xml:"xsi,attr"`
	SchemaLocation string   `xml:"schemaLocation,attr"`
	Title          string   `xml:"title"`
	Text           struct {
		Text     string `xml:",chardata"`
		Texttype string `xml:"texttype,attr"`
	} `xml:"text"`
	Gradable struct {
		Text           string `xml:",chardata"`
		PointsPossible string `xml:"points_possible,attr"`
	} `xml:"gradable"`
	SubmissionFormats struct {
		Text   string `xml:",chardata"`
		Format []struct {
			Text string `xml:",chardata"`
			Type string `xml:"type,attr"`
		} `xml:"format"`
	} `xml:"submission_formats"`
}
