// Code generated by xsdgen. DO NOT EDIT.

package specs

// An Assignment is a simple object for exchanging assignments.
type Assignment struct {
	Title             string                `xml:"http://www.imsglobal.org/xsd/imscc_extensions/assignment title"`
	Text              TextType              `xml:"http://www.imsglobal.org/xsd/imscc_extensions/assignment text,omitempty"`
	Instructortext    TextType              `xml:"http://www.imsglobal.org/xsd/imscc_extensions/assignment instructor_text"`
	Attachments       AttachmentsType       `xml:"http://www.imsglobal.org/xsd/imscc_extensions/assignment attachments,omitempty"`
	Gradable          GradableType          `xml:"http://www.imsglobal.org/xsd/imscc_extensions/assignment gradable,omitempty"`
	Submissionformats SubmissionFormatsType `xml:"http://www.imsglobal.org/xsd/imscc_extensions/assignment submission_formats,omitempty"`
	Extensions        ExtensionsType        `xml:"http://www.imsglobal.org/xsd/imscc_extensions/assignment extensions,omitempty"`
	Identifier        string                `xml:"identifier,attr,omitempty"`
}


type EmptyPrimitiveTypeType struct {
}

// Extensions is the extra information for an assignment that cannot be captured by the current specification. An Assignment object should still be usable and meaningful if the provided extensions cannot be supported by importing systems.
type ExtensionsType struct {
	Items    []string `xml:",any"`
	Platform string   `xml:"platform,attr,omitempty"`
}

type FormatType struct {
	Type Type `xml:"type,attr"`
}

type GradableType struct {
	Value          bool    `xml:",chardata"`
	Pointspossible float32 `xml:"points_possible,attr,omitempty"`
}

// May be one of All, Learner, Manager, Instructor
type Role string

// Specifies the preferred format(s) for a solution to the assignment.
type SubmissionFormatsType struct {
	Format []FormatType `xml:"http://www.imsglobal.org/xsd/imscc_extensions/assignment format"`
}

// This is the explanatory text for the assignment.
type TextType struct {
	Value    string   `xml:",chardata"`
	Texttype Texttype `xml:"texttype,attr"`
}

// May be one of text/plain, text/html
type Texttype string

// May be one of text, html, url, file
type Type string
