// Code generated by xsdgen. DO NOT EDIT.

package specs

type AttachmentType struct {
}

type AttachmentsType struct {
	Attachment []AttachmentType `xml:"http://www.imsglobal.org/xsd/imsccv1p1/imsdt_v1p1 attachment"`
}

// The Topic complexType for the discussion topic object.
type TopicType struct {
	Items       []string        `xml:",any"`
	Title       string          `xml:"http://www.imsglobal.org/xsd/imsccv1p1/imsdt_v1p1 title"`
	Text        TextType        `xml:"http://www.imsglobal.org/xsd/imsccv1p1/imsdt_v1p1 text"`
	Attachments AttachmentsType `xml:"http://www.imsglobal.org/xsd/imsccv1p1/imsdt_v1p1 attachments,omitempty"`
}
